name: absensi_app
description: Aplikasi Absensi Siswa
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  mobile_scanner: ^3.0.0

  # ICON IOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo-absen.png  # Tambahkan baris ini

  # ===== FONT POPPINS LOCAL =====
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800

  # ===== MONTSERRAT =====
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600